server:
  error:
    include-message: always
spring:
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gongcha?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 22295877
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

logging.level:
  org.hibernate.SQL: debug
